language: node_js
node_js: '10'
cache: yarn

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn pr-check
  - yarn deploy
